### ISSUE TITLE
scope question

### ISSUE THREAD

**Issue by alisterburt** [napari/superqt#6]
love the name you went with! I know they're not widgets per-se, but I was wondering if you were thinking of including your `SelectableEventedList/Tree` models and associated views in this repo or if they were out of scope?

**Comment by tlambert03** [comment]
I think in scope!  that's was actually one of the things we [specifically liked](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/widget.20repo.20name.3F/near/241337201) about the name `qt-extras` (and `superqt` by extension)

**Comment by alisterburt** [comment]
❤️  got caught up in name generation and missed that nugget, look forward to it. Do you want a hand bringing them over?

**Comment by tlambert03** [comment]
sure!  I would perhaps like to reconsider some of the name/API choices to make sure that we're making it as qt-like as possible.  but if you're wanting to possible use them more outside of napari, help would be great.  

@sofroniewn do you agree that we want that stuff here?  The biggest "counter argument" is that it depends on the `events.py` stuff... and it does feel kinda gnarly to bring our whole double-events system into this clean environment!  (to be honest, I forgot that until just now... and i think it deserves some thought)

**Comment by alisterburt** [comment]
an excuse to delve into the events system, perfect! Yeah, I would love to have this stuff as a lightweight dependency, it's so fun to work with.

Will wait to see what @sofroniewn says and see where to go from there!

**Comment by sofroniewn** [comment]
> and it does feel kinda gnarly to bring our whole double-events system into this clean environment! (to be honest, I forgot that until just now... and i think it deserves some thought)

eek - maybe, i wouldn't want to duplicate our event system here. Just some rough ideas here

1. We create a `napari-events` package that has our event system that both this repo and the main repo can depend on? Might be good to do regardless

2. Is there a way to have a component here without any of our event system that provides a lot of functionality, but maybe not all the functionality? Or do we make the component use the qt event system instead?

I am a little worried about this repo having both our event system and the qt event system too though .... it might get confusing

**Comment by tlambert03** [comment]
yeah... I don't really love it either :/

this is a longer-term consideration, but one thing I have played with is a python "replica" of the Qt signal/slot syntax (I have always kind of preferred it to our events system... like, `button.clicked.connect(function)` seems nicer than `button.events.clicked.connect(function)`, and I prefer `button.clicked.emit(value)` to `button.events.clicked(value=value)`).  The Qt setup also allows you to better validate the signature of the callback _when_ you connect it (since signals have to be declared with a signature)... which is way better than failing only when you call the callback (and also would make things like https://github.com/napari/magicgui/pull/182 easier).

That all would obviously be a major change in napari. perhaps fine here... but something to think about.
so... @alisterburt, I'm honestly not immediately sure where this leaves us.

> We create a napari-events package that has our event system that both this repo and the main repo can depend on? Might be good to do regardless

yeah, I don't mind that... but if we did that, I'd probably want to really take another hard look at it, and perhaps move away from the vispy events to something like I mentioned above, for the reasons mentioned above.

> Is there a way to have a component here without any of our event system that provides a lot of functionality, but maybe not all the functionality? Or do we make the component use the qt event system instead?

plenty of things, yes... but unfortunately, probably not the container stuff that @alisterburt is talking about here, since all of those containers are basically just setting up a two way connection between a python object with pure python events, and a Qt model/view with Qt signals...

> I am a little worried about this repo having both our event system and the qt event system too though .... it might get confusing

yep, it's confusing enough in napari :joy:

**Comment by sofroniewn** [comment]
> yeah, I don't mind that... but if we did that, I'd probably want to really take another hard look at it, and perhaps move away from the vispy events to something like I mentioned above, for the reasons mentioned above.

hmm yeah, makes sense to me, but that'll probably be a big lift. I'd start in a clean repo for sure, could then see how it felt. i will say i often find the `.events` syntax strange too - especially when dealing with objects with different levels of nesting

**Comment by tlambert03** [comment]
lacking an actionable item here, is it ok if we close this @alisterburt?  To summarize the question posed in the OP:
The scope of this project, as I see it, is to provide things that extend PyQt/PySide2, which includes (but is definitely not limited to) widgets.  The containers from napari definitely feel in scope, but the difficulty with immediately bringing them into this package is the dependency on a Qt-_independent_ event system (which is a little unnatural for this package at the moment).

**Comment by alisterburt** [comment]
nice summary!

**Comment by alisterburt** [comment]
@tlambert03 this popped back into my head today, psygnal now exists so in theory porting/refactoring is now much more actionable...

What do you think is the best path forward? I could take a first pass if you'll look at a PR

**Comment by tlambert03** [comment]
Welp, I guess the first step would be m to create an evented list that uses psygnal instead of eventEmitter... then the rest should be pretty easy

**Comment by alisterburt** [comment]
cool, will start looking at the `EventedList` 👍🏼
